//Array original
const alumnos = [
  "María",
  "José",
  "Ana",
  "Pedro",
  "Lucía",
  "Carlos",
  "Laura",
  "Miguel",
  "Sofía",
  "Luis",
  "Elena",
  "Antonio",
  "Isabel",
  "Francisco",
  "Carmen",
  "David",
  "Raquel",
  "Javier",
  "Patricia",
  "Manuel",
  "Beatriz",
  "Daniel",
  "Natalia",
  "Alejandro",
  "Andrea",
  "Jorge",
  "Eva",
  "Rubén",
  "Silvia",
  "Fernando",
  "Marina",
  "Diego",
  "Cristina",
  "Alberto",
  "Paula",
  "Rafael",
  "Marta",
  "Ignacio",
  "Julia",
  "Ricardo",
  "Celia",
  "Óscar",
  "Nerea",
  "Gonzalo",
  "Virginia",
  "Hugo",
  "Miriam",
  "Adrián",
  "Sara",
  "Roberto",
  "Elena",
  "Álvaro",
  "Teresa",
  "Sergio",
  "Lorena",
  "Víctor",
  "Nuria",
  "Samuel",
  "Alicia",
  "Alonso",
  "Inés",
  "Marcos",
  "Clara",
  "Mario",
  "Irene",
  "Enrique",
  "Elsa",
  "Pablo",
  "Cristina",
  "Lorenzo",
  "Rocío",
  "Joaquín",
  "Angela",
  "Iván",
  "Lucía",
  "Guillermo",
  "Esther",
  "Mariano",
  "Yolanda",
  "Ángel",
  "Nuria",
  "Félix",
  "Begoña",
  "Emilio",
  "Lidia",
  "Héctor",
  "Gema",
  "Israel",
  "Diana",
  "Borja",
  "Victoria",
  "Jaime",
  "Elisa",
  "Martín",
  "Sandra",
  "Tomás",
  "Mónica",
  "Raul",
  "Paloma",
  "Xavier",
  "Cecilia",
  "Esteban",
  "Iris",
  "Paco",
  "Alba",
  "Diego",
  "Ruth",
  "Álex",
  "Berta",
  "Bruno",
  "Vanessa",
  "Josué",
  "Patricia",
  "Óliver",
  "Carolina",
  "Adolfo",
  "Mireia",
  "Iker",
  "Carmen",
  "Aarón",
  "Almudena",
  "Jaime",
  "Clara",
  "Unai",
  "Leticia",
];

//Recupero el h2
const h2 = document.querySelector("h2");
h2.textContent = `Alumnos: ${alumnos.length}`;

//Voy a ordenarlos por orden alfabético
const alumnosOrdenados = alumnos.sort();
//Recupero el ul donde quiero pintar muchos li's
const ul = document.querySelector("ul");
//Recorro en bucle los alumnos ordenados
for (const alumno of alumnosOrdenados) {
  //Por cada uno de ellos creo un li
  const li = document.createElement("li");
  //Le voy a dar el contenido del texto
  li.textContent = alumno;
  //Por cada uno de los lis inyectamelos como hijos en el ul
  ul.appendChild(li);
}
